config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  get 'about' => 'about#show'
  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
    resources :sales, only: [:index, :new, :create]
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  http_basic_authenticate_with name: ENV['ADMIN_USER'].to_s, password: ENV['ADMIN_PASS'].to_s

  def show
  end
end

app/views/admin/dashboard/show.html.erb
<div class="text-center">

  <h1>Admin Dashboard</h1>
  <br>

  <h3>Total products in database</h3>
  <h3><%= Product.count %></h3>
  <h3><%= link_to 'See products', admin_products_path, class: 'btn btn-lg btn-primary' %></h3>

  <h3>Total categories in database</h3>
  <h3><%= Category.count %></h3>
  <h3><%= link_to 'Apparel', class: 'btn btn-lg btn-primary' %></h3>
  <h3><%= link_to 'Electronics', class: 'btn btn-lg btn-primary' %></h3>
  <h3><%= link_to 'Furniture', class: 'btn btn-lg btn-primary' %></h3>
      
</div>